@baseUrl = http://localhost:3001


# @name login
POST {{baseUrl}}/api/login HTTP/1.1
content-type: application/json

{
 "username": "bombom@gmail.com", 
 "password": "secret1"
}

###
@authToken = {{login.response.token}

# @name createComment
POST {{baseUrl}}/api/notes HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
 "author": "mind cafe 666", 
 "url": "http://bing.com",
 "title": "bing"
}


{
 "username": "bombom@gmail.com", 
 "password": "secret1"
}

{
 "username": "john@gmail.com", 
 "password": "secret1"
}

