@baseUrl = http://localhost:3001
@authToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvbWdvZ28zNDUiLCJpZCI6NCwiaWF0IjoxNzIyMzEwMTMwfQ.gDDehLzX1sn1o20RPLYLYitpxGA37ljT43ZR4mYc-Eo


POST {{baseUrl}}/api/blogs HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
 "author": "microsoft", 
 "url": "http://bing.com",
 "title": "bing"
}