POST http://localhost:3001/api/users
content-type: application/json

{
 "username": "bombom@gmail.com", 
 "name": "bom1",
 "password": "secret1"
}

###
POST http://localhost:3001/api/users
content-type: application/json

{
 "username": "bom4", 
 "name": "bom4",
 "password": "secret"
}